name: Default

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Check code formatting with black
        run: |
          pip install black
          black --check humble_rss/
      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 humble_rss/
      - name: Check import order with isort
        run: |
          pip install isort
          python -m isort --profile black --check humble_rss/
      - name: Lint code with mypy
        run: |
          pip install mypy types-beautifulsoup4
          mypy --ignore-missing-imports --install-types --non-interactive humble_rss
